
batch_size: 2
gradient_accumulation_steps: 16
num_epochs: 150
learning_rate: 0.00007
data_root_path: dataset/
ckpt_dir: checkpoint/
log_dir: log/
input_shape: 
  - 512
  - 512
  - 3
encoder: resnet
fine_tune_at: false
augment:
  random_flip: true
  random_cutout: true
  random_contrast: true
  random_brightness: true
model_summary: false
continue_training: false
training: false
